export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST'
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS'
export const PLAN_LIST_FAIL = 'PLAN_LIST_FAIL'

export const PLAN_DETAILS_REQUEST = 'PLAN_DETAILS_REQUEST'
export const PLAN_DETAILS_SUCCESS = 'PLAN_DETAILS_SUCCESS'
export const PLAN_DETAILS_FAIL = 'PLAN_DETAILS_FAIL'